### PR TITLE
Update to Swift 3

### PR DESCRIPTION
**Pull request by TheDarkCode**

### CODE REVIEW

**Comment by sgr-ksmt** [comment]
@TheDarkCode 

Thanks for your replying(#26) and great PR!!!  👍 
But... I just implemented #27 and merged to master. So, this PR has comflicts.
Furthermore, I want to merge this changes not to `master` branch but `swift-3.0` branch.

Could you do following ?  🙇 
- Fix conflicts and push.
- Post new pull request to `swift-3.0` branch.

**Comment by TheDarkCode** [comment]
I will add the changes from #27 (you merged it around the exact time I made this PR) and create a new request for the swift-3.0 branch. I didn't notice the branch until just after.

**Comment by sgr-ksmt** [comment]
>  didn't notice the branch until just after.

I'm sorry that I did not prepare swift-3.0 branch before you created this PR.. 🙇 
After receive your PR, I realized that swift-3.0 branch is needed and created it.

**Comment by TheDarkCode** [comment]
I made a new PR under #29 so I'm going to close this one.

**Comment by sgr-ksmt** [comment]
:bow:

**Pull request closed without merging**
